CREATE DATABASE VentasEmpresaAliada;
GO

USE VentasEmpresaAliada;
GO

-- Tabla DIM_CATEGORY
CREATE TABLE DIM_CATEGORY (
    ID_CATEGORY INT PRIMARY KEY,
    CATEGORY NVARCHAR(255)
);
-- Tabla DIM_PRODUCT
CREATE TABLE DIM_PRODUCT (
    MANUFACTURER NVARCHAR(255),
    BRAND NVARCHAR(255),
    ITEM NVARCHAR(255) PRIMARY KEY,
    ITEM_DESCRIPTION NVARCHAR(255),
    CATEGORY INT,
    FORMAT NVARCHAR(255),
    ATTR1 NVARCHAR(255),
    ATTR2 NVARCHAR(255),
    ATTR3 NVARCHAR(255),
    FOREIGN KEY (CATEGORY) REFERENCES DIM_CATEGORY(ID_CATEGORY)
);
-- Tabla DIM_SEGMENT
CREATE TABLE DIM_SEGMENT (
    CATEGORY INT,
    ATTR1 NVARCHAR(255),
    ATTR2 NVARCHAR(255),
    ATTR3 NVARCHAR(255),
    FORMAT NVARCHAR(255),
    SEGMENT NVARCHAR(255),
    FOREIGN KEY (CATEGORY) REFERENCES DIM_CATEGORY(ID_CATEGORY)
);
-- Tabla DIM_CALENDAR
CREATE TABLE DIM_CALENDAR (
    WEEK NVARCHAR(255) PRIMARY KEY,
    YEAR INT,
    MONTH INT,
    WEEK_NUMBER INT,
    DATE DATE
);
-- Tabla FACT_SALES
CREATE TABLE FACT_SALES (
    WEEK NVARCHAR(255),
    ITEM_CODE NVARCHAR(255),
    TOTAL_UNIT_SALES FLOAT,
    TOTAL_VALUE_SALES FLOAT,
    TOTAL_UNIT_AVG_WEEKLY_SALES FLOAT,
    REGION NVARCHAR(255),
    FOREIGN KEY (WEEK) REFERENCES DIM_CALENDAR(WEEK),
    FOREIGN KEY (ITEM_CODE) REFERENCES DIM_PRODUCT(ITEM)
);
--Consultas
SELECT * FROM DIM_CATEGORY;
SELECT * FROM DIM_PRODUCT;
SELECT * FROM DIM_SEGMENT;
SELECT * FROM DIM_CALENDAR;
SELECT * FROM FACT_SALES;
--Ejecutar uniones entre las tablas
SELECT 
    FS.WEEK,
    DC.CATEGORY,
    FS.REGION,
    SUM(FS.TOTAL_VALUE_SALES) AS Total_Sales
FROM 
    FACT_SALES FS
JOIN DIM_PRODUCT DP ON FS.ITEM_CODE = DP.ITEM
JOIN DIM_CATEGORY DC ON DP.CATEGORY = DC.ID_CATEGORY
GROUP BY 
    FS.WEEK, DC.CATEGORY, FS.REGION
ORDER BY 
    FS.WEEK, Total_Sales DESC;